version: '3.8'
services:
    back:
        container_name: 'back'
        build: .
        depends_on:
            - postgres
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./.env:/opt/app/.env
    postgres:
        container_name: 'postgres-db'
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=store
        ports:
            - '5432:5432'
        volumes:
            - /var/folders/postgres-data:/var/lib/postgresql/data
